/*
 * Copyright 2016 FabricMC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.fabricmc.loader.impl.wasm;

import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import net.fabricmc.loader.impl.wasm.runtime.HookArgs;
import net.fabricmc.loader.impl.wasm.runtime.HookOutcome;
import net.fabricmc.loader.impl.wasm.runtime.WasmHookDispatcher;

/**
 * The entry point generated Mixin handlers call.
 *
 * <p>Everything here is public and static because it is reached from bytecode woven into game
 * classes. Arguments are pushed one at a time into a per-thread arena rather than boxed into an
 * {@code Object[]}, so that a hook firing every tick allocates nothing; the generated bytecode is
 * also simpler that way, being a flat run of loads and static calls with no array construction.
 *
 * <p>The decision logic -- cancelling, substituting return values, choosing what to do when the
 * guest cannot be entered -- lives here rather than in generated code, so that the generator only
 * ever emits one shape per hook kind.
 */
public final class WasmHooks {
	private WasmHooks() { }

	/**
	 * Starts a hook invocation. Always paired with exactly one terminating call below.
	 */
	public static void begin(int hookId) {
		HookArgs.current().begin(hookId);
	}

	public static void pushObject(Object value) {
		HookArgs.current().pushObject(value);
	}

	public static void pushBoolean(boolean value) {
		HookArgs.current().pushInt(value ? 1 : 0);
	}

	public static void pushByte(byte value) {
		HookArgs.current().pushInt(value);
	}

	public static void pushChar(char value) {
		HookArgs.current().pushInt(value);
	}

	public static void pushShort(short value) {
		HookArgs.current().pushInt(value);
	}

	public static void pushInt(int value) {
		HookArgs.current().pushInt(value);
	}

	public static void pushLong(long value) {
		HookArgs.current().pushLong(value);
	}

	public static void pushFloat(float value) {
		HookArgs.current().pushFloat(value);
	}

	public static void pushDouble(double value) {
		HookArgs.current().pushDouble(value);
	}

	/**
	 * Terminates an inject hook on a void returning target.
	 */
	public static void inject(int hookId, CallbackInfo ci) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);

		if (outcome.isCancel()) ci.cancel();
	}

	/**
	 * Terminates an inject hook on a value returning target.
	 */
	@SuppressWarnings({"unchecked", "rawtypes"})
	public static void injectReturnable(int hookId, CallbackInfoReturnable cir) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);

		if (!outcome.isCancel()) return;

		if (outcome.hasValue()) {
			cir.setReturnValue(outcome.asBoxed(WasmHookDispatcher.returnTypeOf(hookId)));
		} else {
			cir.cancel();
		}
	}

	public static boolean valueBoolean(int hookId, boolean current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? outcome.asInt() != 0 : current;
	}

	public static byte valueByte(int hookId, byte current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? (byte) outcome.asInt() : current;
	}

	public static char valueChar(int hookId, char current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? (char) outcome.asInt() : current;
	}

	public static short valueShort(int hookId, short current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? (short) outcome.asInt() : current;
	}

	public static int valueInt(int hookId, int current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? outcome.asInt() : current;
	}

	public static long valueLong(int hookId, long current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? outcome.asLong() : current;
	}

	public static float valueFloat(int hookId, float current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? outcome.asFloat() : current;
	}

	public static double valueDouble(int hookId, double current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? outcome.asDouble() : current;
	}

	public static Object valueObject(int hookId, Object current) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		return outcome.hasValue() ? outcome.asObject() : current;
	}

	/**
	 * Runs a redirect hook's guest call and stashes the result.
	 *
	 * <p>Mixin removes the original invocation, so a handler that declines to act still has to
	 * produce a value. Returning zero tells the generated handler to perform the original call
	 * itself, which is the only branch in any generated method.
	 *
	 * @return non-zero if the guest supplied a replacement value, zero to fall through
	 */
	public static int redirectStatus(int hookId) {
		HookOutcome outcome = WasmHookDispatcher.dispatch(hookId);
		HookOutcome.stash(outcome);
		return outcome.hasValue() ? 1 : 0;
	}

	public static boolean resultBoolean(int hookId) {
		return HookOutcome.takeStashed().asInt() != 0;
	}

	public static byte resultByte(int hookId) {
		return (byte) HookOutcome.takeStashed().asInt();
	}

	public static char resultChar(int hookId) {
		return (char) HookOutcome.takeStashed().asInt();
	}

	public static short resultShort(int hookId) {
		return (short) HookOutcome.takeStashed().asInt();
	}

	public static int resultInt(int hookId) {
		return HookOutcome.takeStashed().asInt();
	}

	public static long resultLong(int hookId) {
		return HookOutcome.takeStashed().asLong();
	}

	public static float resultFloat(int hookId) {
		return HookOutcome.takeStashed().asFloat();
	}

	public static double resultDouble(int hookId) {
		return HookOutcome.takeStashed().asDouble();
	}

	public static Object resultObject(int hookId) {
		return HookOutcome.takeStashed().asObject();
	}
}
