/*
 * Copyright 2016 FabricMC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.fabricmc.loader.impl.wasm.runtime;

import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.ReentrantLock;

import net.fabricmc.loader.impl.util.log.Log;
import net.fabricmc.loader.impl.util.log.LogCategory;
import net.fabricmc.loader.impl.wasm.WasmModEntry;

/**
 * A single WebAssembly mod's guest instance and everything guarding access to it.
 *
 * <p>One instance per mod, guarded by one lock. Per-thread instances were rejected: each would get
 * its own linear memory, so the mod's global state would silently fork per thread, which is a
 * correctness bug dressed up as a performance decision. An instance pool has the same problem.
 *
 * <p>Reentrancy is refused rather than supported. The WebAssembly stack itself survives being
 * re-entered, but the guest side bindings generated by current tooling keep their return area in a
 * mutable static: while an outer call sits suspended inside a host import, a nested call overwrites
 * that area, and the outer call then reads rubbish when it resumes. The host cannot fix this because
 * the guest owns the area, so the only safe answer is not to enter.
 */
public final class WasmModInstance {
	/**
	 * Export called once before any hook, so that a guest built against a different ABI revision is
	 * caught immediately rather than by way of silently mismatched arguments.
	 */
	private static final String EXPORT_ABI_VERSION = "abi-version";
	private static final String EXPORT_INIT = "init";
	private static final String EXPORT_ON_HOOK = "on-hook";
	private static final String EXPORT_REALLOC = "cabi_realloc";

	/**
	 * Post-return companion of {@link #EXPORT_ON_HOOK}.
	 *
	 * <p>The component model carries this as a canonical option rather than a name. Resolving it by
	 * convention is a deliberate simplification of the decoder; it matches what current tooling
	 * emits, and a guest that does not provide it simply needs no cleanup.
	 */
	private static final String EXPORT_POST_RETURN = "cabi_post_on-hook";

	/**
	 * How long a hook waits for the lock before giving up. Blocking forever would turn a stutter
	 * into a hang, and the two are indistinguishable from the outside.
	 */
	private static final long LOCK_TIMEOUT_MS = 250;

	private final WasmModEntry entry;
	private final ReentrantLock lock = new ReentrantLock();
	private final HandleTable handles = new HandleTable();

	private WasmInstance instance;
	private GuestAllocator allocator;
	private boolean hasPostReturn;
	private int depth;
	private boolean warnedAboutReentrancy;
	private boolean warnedAboutContention;
	private boolean broken;

	public WasmModInstance(WasmModEntry entry) {
		this.entry = entry;
	}

	public WasmModEntry getEntry() {
		return entry;
	}

	public HandleTable getHandles() {
		return handles;
	}

	/**
	 * Instantiates the guest and runs its initialiser. Called once, before any hook can fire.
	 */
	public void start() {
		lock.lock();

		try {
			byte[] coreModule = Files.readAllBytes(entry.getCoreModulePath());
			List<WasmHostFunction> imports = new ArrayList<>(HostBindings.create(this));

			instance = WasmEngineProvider.get().instantiate(coreModule, imports);
			allocator = createAllocator(instance);
			hasPostReturn = instance.hasExport(EXPORT_POST_RETURN);

			checkAbiVersion();
			instance.call(EXPORT_INIT, new long[0]);

			Log.debug(LogCategory.GENERAL, "Started WebAssembly mod %s", entry.getModId());
		} catch (IOException e) {
			throw new WasmExecutionException("failed to read the core module of " + entry, e);
		} finally {
			lock.unlock();
		}
	}

	private void checkAbiVersion() {
		if (!instance.hasExport(EXPORT_ABI_VERSION)) {
			throw new WasmExecutionException(entry + " does not export '" + EXPORT_ABI_VERSION
					+ "', so its ABI revision cannot be checked");
		}

		long reported = instance.call(EXPORT_ABI_VERSION, new long[0])[0];

		if (reported != net.fabricmc.loader.impl.wasm.WasmConstants.SUPPORTED_ABI_VERSION) {
			throw new WasmExecutionException(String.format(
					"%s was built against WebAssembly ABI revision %d, but this loader implements revision %d",
					entry, reported, net.fabricmc.loader.impl.wasm.WasmConstants.SUPPORTED_ABI_VERSION));
		}
	}

	/**
	 * Runs a hook in the guest.
	 *
	 * @param localHookId the mod-local hook index the guest dispatches on
	 * @return what the guest asked for, or {@link HookOutcome#PROCEED_OUTCOME} whenever the guest
	 *     could not safely be entered
	 */
	public HookOutcome dispatch(int localHookId, HookArgs args) {
		// every path that does not reach invoke() has to clear the arena itself: the handler has
		// already pushed its arguments, and leaving them there would keep game objects reachable
		// until that thread's next hook fires
		if (broken) return skip(args);

		boolean locked;

		try {
			locked = lock.tryLock(LOCK_TIMEOUT_MS, TimeUnit.MILLISECONDS);
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			return skip(args);
		}

		if (!locked) {
			warnOnceAboutContention();
			return skip(args);
		}

		try {
			if (depth > 0 && !entry.getSpec().isReentrant()) {
				warnOnceAboutReentrancy();
				return skip(args);
			}

			return invoke(localHookId, args);
		} finally {
			lock.unlock();
		}
	}

	private static HookOutcome skip(HookArgs args) {
		args.clear();
		return HookOutcome.PROCEED_OUTCOME;
	}

	private HookOutcome invoke(int localHookId, HookArgs args) {
		int mark = handles.openScope();
		depth++;
		int resultPointer = 0;

		try {
			int argsPointer = CanonicalAbi.lowerArgs(instance, allocator, args, handles);
			long[] result = instance.call(EXPORT_ON_HOOK,
					new long[] {localHookId, argsPointer & 0xffffffffL, args.size()});

			if (result.length != 1) {
				throw new WasmExecutionException("expected '" + EXPORT_ON_HOOK + "' to return one value, got "
						+ result.length);
			}

			resultPointer = (int) result[0];
			return CanonicalAbi.liftOutcome(instance, resultPointer, handles);
		} catch (WasmExecutionException e) {
			// a trapped guest has undefined linear memory from here on, so stop calling into it
			broken = true;
			Log.error(LogCategory.GENERAL, "Disabling WebAssembly mod %s after an unrecoverable error in hook %d",
					entry.getModId(), localHookId, e);
			return HookOutcome.PROCEED_OUTCOME;
		} finally {
			// post-return has to run after the result has been read and exactly once, otherwise the
			// guest keeps or frees the wrong memory
			if (hasPostReturn && resultPointer != 0 && !broken) {
				try {
					instance.call(EXPORT_POST_RETURN, new long[] {resultPointer & 0xffffffffL});
				} catch (WasmExecutionException e) {
					Log.warn(LogCategory.GENERAL, "%s failed to clean up after hook %d", entry.getModId(),
							localHookId, e);
				}
			}

			depth--;
			handles.closeScope(mark);
			args.clear();
		}
	}

	private static GuestAllocator createAllocator(final WasmInstance instance) {
		if (!instance.hasExport(EXPORT_REALLOC)) {
			// only needed once a hook actually passes arguments, so this is not fatal on its own
			return new GuestAllocator() {
				@Override
				public int realloc(int oldPtr, int oldSize, int align, int newSize) {
					throw new WasmExecutionException("guest does not export '" + EXPORT_REALLOC
							+ "', so the host cannot pass it any arguments");
				}
			};
		}

		return new GuestAllocator() {
			@Override
			public int realloc(int oldPtr, int oldSize, int align, int newSize) {
				long[] ret = instance.call(EXPORT_REALLOC, new long[] {oldPtr, oldSize, align, newSize});
				return (int) ret[0];
			}
		};
	}

	private void warnOnceAboutReentrancy() {
		if (warnedAboutReentrancy) return;

		warnedAboutReentrancy = true;
		Log.warn(LogCategory.GENERAL, "Skipping a re-entered hook of WebAssembly mod %s. A hook called back into "
				+ "the game and that call triggered another of its own hooks, which its bindings cannot survive. "
				+ "Further occurrences are not logged.", entry.getModId());
	}

	private void warnOnceAboutContention() {
		if (warnedAboutContention) return;

		warnedAboutContention = true;
		Log.warn(LogCategory.GENERAL, "A hook of WebAssembly mod %s waited more than %d ms for the mod to become "
				+ "available and was skipped. Further occurrences are not logged.", entry.getModId(), LOCK_TIMEOUT_MS);
	}
}
